import type { Metadata } from "next";
import { DM_Sans, Lora } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";


const lora = Lora({
  subsets:["latin"],
  weight:["400", "500"],
  style: ["normal", "italic"],
  variable: "--font-serif"
})

const dmSans = DM_Sans({
  subsets:["latin"],
  weight:["300", "400", "500", "600"],
  variable: "--font-sans"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons:{
    icon: "/Logo1.png"
  }
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${lora.variable} ${dmSans.variable}`}>
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange>
          <Header/>
          <main>
        {children}
          </main>
        </ThemeProvider>
        </body>
    </html>
  );
}
